// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAqFEBmFrYarY8X5-8Bhngz8lndSYNpM8',
    appId: '1:751411734893:web:6171a5c7562d75bd54d264',
    messagingSenderId: '751411734893',
    projectId: 'lami-art-studio-web',
    authDomain: 'lami-art-studio-web.firebaseapp.com',
    storageBucket: 'lami-art-studio-web.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMb5TtCOZTA8vhOnJJP9rx2dWye2DECiY',
    appId: '1:751411734893:android:667c363f35dff4b254d264',
    messagingSenderId: '751411734893',
    projectId: 'lami-art-studio-web',
    storageBucket: 'lami-art-studio-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAggpIvjSlWw92xMO6NcKUhdmzwAN4gtIk',
    appId: '1:751411734893:ios:7fbaf0bf0df85f0b54d264',
    messagingSenderId: '751411734893',
    projectId: 'lami-art-studio-web',
    storageBucket: 'lami-art-studio-web.firebasestorage.app',
    iosBundleId: 'com.example.lamiartstudioWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAggpIvjSlWw92xMO6NcKUhdmzwAN4gtIk',
    appId: '1:751411734893:ios:7fbaf0bf0df85f0b54d264',
    messagingSenderId: '751411734893',
    projectId: 'lami-art-studio-web',
    storageBucket: 'lami-art-studio-web.firebasestorage.app',
    iosBundleId: 'com.example.lamiartstudioWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAqFEBmFrYarY8X5-8Bhngz8lndSYNpM8',
    appId: '1:751411734893:web:fd5d5466e4b071cb54d264',
    messagingSenderId: '751411734893',
    projectId: 'lami-art-studio-web',
    authDomain: 'lami-art-studio-web.firebaseapp.com',
    storageBucket: 'lami-art-studio-web.firebasestorage.app',
  );
}
