import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'home_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Lami Art Studio',
      debugShowCheckedModeBanner: false,
      home: HomePage(), // Your homepage with AppBar
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // Custom AppBar with image background
      appBar: PreferredSize(
        preferredSize: const Size.fromHeight(80),
        child: AppBar(
          automaticallyImplyLeading: false,
          backgroundColor: Colors.white,
          flexibleSpace: Container(
            // decoration: const BoxDecoration(
            //   image: DecorationImage(
            //     image: AssetImage('assets/images/lamiart_bg.png'),
            //     fit: BoxFit.cover,
            //   ),
            // ),
            child: Center(
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    // Left side: logo + company name, perfectly centered vertically
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Center(
                          child: Image.asset(
                            'assets/images/lamiart_logo.png',
                            height: 80,
                          ),
                        ),
                        const SizedBox(width: 20),

                        const Text(
                          "Lami Art  Studio",
                          style: TextStyle(
                            fontFamily: 'Calligraphy',
                            fontSize: 42,
                            color: Color.fromARGB(255, 195, 140, 0),
                          ),
                        ),
                        // Center(
                        //   child: Image.asset(
                        //     'assets/images/lamiart_name.png',
                        //     height: 40,
                        //   ),
                        // ),
                      ],
                    ),
                    // Right side: navigation menu
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        TextButton(
                          onPressed: () {},
                          child: const Text(
                            'Home',
                            style: TextStyle(
                              color: Color.fromARGB(255, 195, 140, 0),
                              fontFamily: 'AppleGaramond',
                              fontSize: 22,
                            ),
                          ),
                        ),
                        const SizedBox(width: 20),
                        TextButton(
                          onPressed: () {},
                          child: const Text(
                            'Gallery',
                            style: TextStyle(
                              color: Color.fromARGB(255, 195, 140, 0),
                              fontFamily: 'AppleGaramond',
                              fontSize: 22,
                            ),
                          ),
                        ),
                        const SizedBox(width: 20),
                        TextButton(
                          onPressed: () {},
                          child: const Text(
                            'Contact Us',
                            style: TextStyle(
                              color: Color.fromARGB(255, 195, 140, 0),
                              fontFamily: 'AppleGaramond',
                              fontSize: 22,
                            ),
                          ),
                        ),
                        const SizedBox(width: 30),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ),
          //backgroundColor: Colors.transparent,
          elevation: 0,
        ),
      ),
      body: const HomePageContent(), // your homepage content widget
    );
  }
}
